output-filename: babel-only-chests.zip
books-path: books

add-crafting-recipe: false

add-fishing-loot: false
add-village-loot: true
add-mansion-loot: true
add-stronghold-loot: true
add-zombie-drop: false
replace-hero-of-the-village-gift: false

copy-of-copy-chance: 0.66
copy-of-original-chance: 0.1
original-chance: 0.003

indent-output: false
