output-filename: babel-no-copying.zip
books-path: books

add-crafting-recipe: false

add-fishing-loot: true
add-village-loot: true
add-mansion-loot: true
add-stronghold-loot: true
add-zombie-drop: true
# Disable hero of village, since it gives duplicable books
replace-hero-of-the-village-gift: false

# Books are always copy-of-copy
copy-of-copy-chance: 1
copy-of-original-chance: 0
original-chance: 0

# Indent output json files
indent-output: false
