# Outputted data pack file
output-filename: babel.zip
# Path containing the book json / yaml files
books-path: lore_books

# Include a recipe to craft random pre-written books. See `README.md` for the recipe.
# Crafted books have the special lore text "Soulwritten"
add-crafting-recipe: false

# Find pre-written books while fishing
# Fished books have the special lore text "Waterlogged"
add-fishing-loot: true
# Find pre-written books in village chests
add-village-loot: true
# Find pre-written books in Woodland Mansions
add-mansion-loot: true
# Find pre-written books in Stronghold Libraries
add-stronghold-loot: true
# Zombies rarely drop pre-written books, if killed by a player
add-zombie-drop: false
# If you are hero of the village, a librarian may gift you a pre-written book
# This ignores the below chances and gives a copy-of-original 90% of the time, and an original 10%.
replace-hero-of-the-village-gift: true
# Add lost lost libraries with book loot to world generation
add-lost-libraries: true
# Add test loot tables. To get a copy of every book in shulker boxes, run the command:
# /loot give @s loot babel:metabox
add-metabox: false

# By default books are "Tattered."
# Each of these chances will be applied in this order, regardless of the outcome of previous rolls.
copy-of-copy-chance: 0.95
copy-of-original-chance: 0.05
original-chance: 0.003

# Loot table weights. Higher numbers mean more likely to be chosen.
# Keep in mind these values are relative to others from the same loot table,
# so the same number can have different effects for each.
weights:
  stronghold-library: 15
  woodland-mansion: 5
  village: 3
  fishing: 1
  zombie: 1

# Indent output json files
indent-output: false
