output-filename: babel-no-libraries.zip
books-path: lore_books

add-crafting-recipe: false

add-fishing-loot: true
add-village-loot: true
add-mansion-loot: true
add-stronghold-loot: true
add-zombie-drop: false
replace-hero-of-the-village-gift: true
add-lost-libraries: false
add-test-tables: false

copy-of-copy-chance: 0.95
copy-of-original-chance: 0.05
original-chance: 0.003

indent-output: false
