output-filename: babel-only-chests.zip
books-path: lore_books

add-crafting-recipe: false

add-fishing-loot: false
add-village-loot: true
add-mansion-loot: true
add-stronghold-loot: true
add-zombie-drop: false
replace-hero-of-the-village-gift: false
add-lost-libraries: true
add-metabox: false

copy-of-copy-chance: 0.95
copy-of-original-chance: 0.05
original-chance: 0.003

weights:
  stronghold-library: 15
  woodland-mansion: 5
  village: 3
  fishing: 1
  zombie: 1

indent-output: false
