output-filename: babel-recipe.zip
books-path: lore_books

add-crafting-recipe: true

add-fishing-loot: true
add-village-loot: true
add-mansion-loot: true
add-stronghold-loot: true
add-zombie-drop: true
replace-hero-of-the-village-gift: true
add-lost-libraries: true

copy-of-copy-chance: 0.9
copy-of-original-chance: 0.05
original-chance: 0.003

indent-output: false
